FROM node:20 AS frontend-build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install --legacy-peer-deps
COPY . ./
EXPOSE 8080
CMD ["npm", "run", "start", "--", "--host=0.0.0.0", "--port=8080"]