"""initial schema

Revision ID: 9ccf13f9b72b
Revises: 
Create Date: 2025-10-29 01:04:39.149141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ccf13f9b72b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_types',
    sa.Column('alert_type_id', sa.UUID(), nullable=False),
    sa.Column('type_name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('alert_type_id'),
    sa.UniqueConstraint('code', name='uq_alert_types_code'),
    sa.UniqueConstraint('type_name', name='uq_alert_types_name')
    )
    op.create_table('event_types',
    sa.Column('event_type_id', sa.UUID(), nullable=False),
    sa.Column('type_name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('event_type_id'),
    sa.UniqueConstraint('code', name='uq_event_types_code'),
    sa.UniqueConstraint('type_name', name='uq_event_types_name')
    )
    op.create_table('leagues',
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('sport_code', sa.String(), nullable=False),
    sa.Column('league_code', sa.String(), nullable=False),
    sa.Column('league_name', sa.String(), nullable=False),
    sa.Column('espn_league_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('league_id'),
    sa.UniqueConstraint('espn_league_id'),
    sa.UniqueConstraint('sport_code', 'league_code', name='uq_leagues_sport_league_code')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('clerk_id', sa.String(), nullable=True),
    sa.Column('username', postgresql.CITEXT(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('profile_picture_url', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('clerk_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('venues',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state_region', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('is_indoor', sa.Boolean(), nullable=True),
    sa.Column('espn_venue_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('latitude IS NULL OR (latitude BETWEEN -90 AND 90)', name='chk_lat_range'),
    sa.CheckConstraint('longitude IS NULL OR (longitude BETWEEN -180 AND 180)', name='chk_lon_range'),
    sa.PrimaryKeyConstraint('venue_id'),
    sa.UniqueConstraint('espn_venue_id'),
    sa.UniqueConstraint('name', 'city', 'state_region', 'country', name='uq_venues_name_location')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('sport_league', sa.String(), nullable=False),
    sa.Column('sport_conference', sa.String(), nullable=True),
    sa.Column('sport_division', sa.String(), nullable=True),
    sa.Column('home_location', sa.String(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('home_venue_id', sa.UUID(), nullable=True),
    sa.Column('espn_team_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['home_venue_id'], ['venues.venue_id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ),
    sa.PrimaryKeyConstraint('team_id'),
    sa.UniqueConstraint('espn_team_id'),
    sa.UniqueConstraint('league_id', 'home_location', 'team_name', name='uq_teams_league_location_name')
    )
    op.create_table('games',
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('home_team_id', sa.UUID(), nullable=False),
    sa.Column('away_team_id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('home_team_id <> away_team_id', name='chk_game_distinct_teams'),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.venue_id'], ),
    sa.PrimaryKeyConstraint('game_id'),
    sa.UniqueConstraint('league_id', 'home_team_id', 'away_team_id', 'date_time', name='uq_games_league_teams_datetime')
    )
    op.create_table('team_chats',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message_text', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('ix_team_chats_team_timestamp', 'team_chats', ['team_id', 'timestamp'], unique=False)
    op.create_table('user_favorite_teams',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'team_id')
    )
    op.create_table('events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('creator_user_id', sa.UUID(), nullable=False),
    sa.Column('event_type_id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=True),
    sa.Column('venue_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('game_date', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('latitude IS NULL OR (latitude BETWEEN -90 AND 90)', name='chk_event_lat_range'),
    sa.CheckConstraint('longitude IS NULL OR (longitude BETWEEN -180 AND 180)', name='chk_event_lon_range'),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.event_type_id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.venue_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_events_game_date', 'events', ['game_date'], unique=False)
    op.create_table('safety_alerts',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('reporter_user_id', sa.UUID(), nullable=False),
    sa.Column('alert_type_id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=True),
    sa.Column('venue_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('game_date', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latitude IS NULL OR (latitude BETWEEN -90 AND 90)', name='chk_alert_lat_range'),
    sa.CheckConstraint('longitude IS NULL OR (longitude BETWEEN -180 AND 180)', name='chk_alert_lon_range'),
    sa.ForeignKeyConstraint(['alert_type_id'], ['alert_types.alert_type_id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.venue_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index('ix_alerts_game_date', 'safety_alerts', ['game_date'], unique=False)
    op.create_table('favorites',
    sa.Column('favorite_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('game_id', sa.UUID(), nullable=True),
    sa.Column('date_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(event_id IS NOT NULL AND game_id IS NULL) OR (event_id IS NULL AND game_id IS NOT NULL)', name='ck_favorites_event_xor_game'),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('favorite_id')
    )
    op.create_index('uq_fav_event_per_user', 'favorites', ['user_id', 'event_id'], unique=True, postgresql_where=sa.text('event_id IS NOT NULL'))
    op.create_index('uq_fav_game_per_user', 'favorites', ['user_id', 'game_id'], unique=True, postgresql_where=sa.text('game_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_fav_game_per_user', table_name='favorites', postgresql_where=sa.text('game_id IS NOT NULL'))
    op.drop_index('uq_fav_event_per_user', table_name='favorites', postgresql_where=sa.text('event_id IS NOT NULL'))
    op.drop_table('favorites')
    op.drop_index('ix_alerts_game_date', table_name='safety_alerts')
    op.drop_table('safety_alerts')
    op.drop_index('ix_events_game_date', table_name='events')
    op.drop_table('events')
    op.drop_table('user_favorite_teams')
    op.drop_index('ix_team_chats_team_timestamp', table_name='team_chats')
    op.drop_table('team_chats')
    op.drop_table('games')
    op.drop_table('teams')
    op.drop_table('venues')
    op.drop_table('users')
    op.drop_table('leagues')
    op.drop_table('event_types')
    op.drop_table('alert_types')
    # ### end Alembic commands ###
